/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsDiagnostic {
  /** Human-readable diagnostic message. */
  message: string
}

export interface JsParseOptions {
  /** Suppress tag recognition inside fenced code blocks. Default: true. */
  fenceAware?: boolean
  /** Enable type expression parsing for `{...}` in tags. Default: false. */
  parseTypes?: boolean
  /** Parse mode for type expressions: "jsdoc", "closure", or "typescript". Default: "jsdoc". */
  typeParseMode?: string
  /** Enable jsdoccomment-compat extension fields. Default: false. */
  compatMode?: boolean
  /** Original-file absolute byte offset of `source_text`. Default: 0. */
  baseOffset?: number
}

export interface JsParseResult {
  /**
   * Encoded Binary AST bytes — pass to `@ox-jsdoc/decoder`'s
   * `RemoteSourceFile` constructor.
   */
  buffer: Uint8Array
  /**
   * Parser diagnostics (also embedded in the binary buffer's
   * Diagnostics section, surfaced here for convenience).
   */
  diagnostics: Array<JsDiagnostic>
}

/** Parse a complete `/** ... *\/` JSDoc block and return the Binary AST. */
export declare function parseJsdoc(
  sourceText: string,
  options?: JsParseOptions | undefined | null
): JsParseResult
