/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsBatchDiagnostic {
  /** Human-readable diagnostic message. */
  message: string
  /** Index of the input item this diagnostic belongs to (`0..items.len()`). */
  rootIndex: number
}

export interface JsBatchItem {
  /** `/** ... *\/` source text for this comment. */
  sourceText: string
  /** Original-file absolute byte offset. Default: 0. */
  baseOffset?: number
}

export interface JsBatchParseResult {
  /**
   * Encoded Binary AST bytes — pass to `@ox-jsdoc/decoder`'s
   * `RemoteSourceFile` constructor; one buffer carries N roots.
   */
  buffer: Uint8Array
  /**
   * Parser diagnostics for the entire batch (input order). Use
   * `root_index` to attribute each diagnostic back to a `BatchItem`.
   */
  diagnostics: Array<JsBatchDiagnostic>
}

export interface JsDiagnostic {
  /** Human-readable diagnostic message. */
  message: string
}

export interface JsParseOptions {
  /** Suppress tag recognition inside fenced code blocks. Default: true. */
  fenceAware?: boolean
  /** Enable type expression parsing for `{...}` in tags. Default: false. */
  parseTypes?: boolean
  /** Parse mode for type expressions: "jsdoc", "closure", or "typescript". Default: "jsdoc". */
  typeParseMode?: string
  /** Enable jsdoccomment-compat extension fields. Default: false. */
  compatMode?: boolean
  /** Original-file absolute byte offset of `source_text`. Default: 0. */
  baseOffset?: number
}

export interface JsParseResult {
  /**
   * Encoded Binary AST bytes — pass to `@ox-jsdoc/decoder`'s
   * `RemoteSourceFile` constructor.
   */
  buffer: Uint8Array
  /**
   * Parser diagnostics (also embedded in the binary buffer's
   * Diagnostics section, surfaced here for convenience).
   */
  diagnostics: Array<JsDiagnostic>
}

/**
 * Diagnostic: pay only the input-side marshalling cost (Vec<JsBatchItem>
 * auto-conversion). Returns the item count so the call cannot be DCE'd.
 */
export declare function napiMarshallingInOnly(items: Array<JsBatchItem>): number

/**
 * Diagnostic: pay only the output-side marshalling cost (Vec<u8> →
 * `Uint8Array` ownership transfer). Allocates a zero-filled buffer of
 * `size` bytes and hands it to NAPI.
 */
export declare function napiMarshallingOutOnly(size: number): Uint8Array

/** Parse a complete `/** ... *\/` JSDoc block and return the Binary AST. */
export declare function parseJsdoc(
  sourceText: string,
  options?: JsParseOptions | undefined | null
): JsParseResult

/**
 * Parse N JSDoc block comments into a single shared Binary AST buffer.
 *
 * The returned buffer carries N roots side-by-side; the JS-side decoder
 * exposes them via `RemoteSourceFile.asts`. Strings recur across comments
 * (`*`, `*\/`, common tag names) are interned once for the whole batch.
 */
export declare function parseJsdocBatch(
  items: Array<JsBatchItem>,
  options?: JsParseOptions | undefined | null
): JsBatchParseResult

/**
 * Parse N JSDoc block comments where the JS-side has already concatenated
 * every `source_text` into a single UTF-8 byte buffer.
 *
 * This avoids the per-item `Vec<JsBatchItem>` auto-conversion that
 * dominates the [`parse_jsdoc_batch`] NAPI call (~213 µs / ~30% of the
 * full call for the 226-comment fixture). Three NAPI handles replace
 * 226 × {object, string, number} conversions:
 *
 * - `concat`: every `source_text` UTF-8 byte concatenated, no separators.
 * - `offsets`: length `N + 1`. `concat[offsets[i]..offsets[i+1]]` is the
 *   bytes for input item `i`.
 * - `base_offsets`: length `N`. Per-item `base_offset`.
 *
 * The JS wrapper (`parseBatch` in `index.js`) builds those views via
 * `TextEncoder`. Callers who need the original ergonomic API can keep
 * using [`parse_jsdoc_batch`].
 */
export declare function parseJsdocBatchRaw(
  concat: Uint8Array,
  offsets: Uint32Array,
  baseOffsets: Uint32Array,
  options?: JsParseOptions | undefined | null
): JsBatchParseResult
