packages:
  - 'napi/*'
  - 'packages/*'
  - 'tasks/*'
  - 'wasm/*'
  - apps/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  '@types/node': ^25.9.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest

minimumReleaseAgeExclude:
  - '@kazupon/vp-config'
  - 'wasm-pack'

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
