/**
 * @author kazuya kawaguchi (a.k.a. kazupon)
 * @license MIT
 */

// @ts-check

import init, { parse as parseWasm } from '../pkg/ox_jsdoc_wasm.js'

let initialized = false

/**
 * Initialize the WASM module.
 *
 * Must be called once before `parse()`. Fetches and compiles the `.wasm`
 * binary. Subsequent calls are no-ops.
 *
 * @param {string | URL | Request | Response | WebAssembly.Module | ArrayBuffer | BufferSource} [wasmUrl]
 *   Custom URL or source for the `.wasm` file. When omitted the default
 *   path generated by wasm-pack is used.
 * @returns {Promise<void>}
 */
export async function initWasm(wasmUrl) {
  if (!initialized) {
    await init(wasmUrl)
    initialized = true
  }
}

/**
 * Parse a complete `/** ... *​/` JSDoc block comment.
 *
 * @param {string} sourceText
 * @param {{ fenceAware?: boolean }} [options]
 * @returns {{ ast: any, diagnostics: Array<{ message: string }> }}
 */
export function parse(sourceText, options) {
  if (!initialized) {
    throw new Error('Call initWasm() before parse()')
  }
  const result = parseWasm(sourceText, options?.fenceAware)
  return {
    get ast() {
      const value = result.astJson === 'null' ? null : JSON.parse(result.astJson)
      Object.defineProperty(this, 'ast', { value })
      return value
    },
    diagnostics: result.diagnostics
  }
}
